"""empty message

Revision ID: 011f40808a00
Revises: 
Create Date: 2018-02-08 16:56:00.881228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011f40808a00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_body', sa.String(), nullable=True),
    sa.Column('q_author', sa.String(length=255), nullable=True),
    sa.Column('p_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
