"""Edited photos

Revision ID: 759091c78bd5
Revises: 875e16e726f3
Create Date: 2018-02-12 20:06:03.987558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759091c78bd5'
down_revision = '875e16e726f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profile_photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_photos',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pic_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profile_photos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_photos_pkey')
    )
    op.drop_table('photos')
    # ### end Alembic commands ###
